config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'users/new'
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/login", to: "sessions#destroy"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  VALID_EMAIL_REGEX = Settings.validate.user.email_regex
  attr_accessor :remember_token

  before_save { email.downcase! }

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  class << self
    # Returns the hash digest of the given string.
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    #Returns a random token
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  private

  def downcase_email
    email.downcase
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
  
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def hello
    render html: 'hello, world!!'
  end

  def goodbye
    render html: 'goodbye, world!'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate params[:session][:password]
      flash[:success] = "Login success"
      log_in user
      params[:session][:remember] == Settings.number.remember ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user, except: %i(show new create)
  before_action :correct_user, only: %i(edit update)
  before_action :admin_user, only: :destroy
  before_action :find_user, only: %i(show edit update)

  def show
  end
    
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def find_user
      @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  #Returns the full title on a per-page basic.
  def full_title(page_title = '')
    base_title = 'Ruby on Rails Tutorial Sample App'
    return (page_title + " | " + base_title) unless page_title.empty?
    base_title
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by id: user_id
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by id: user_id
      if user&.authenticated? cookies[:remember_token]
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  # Forgets a persistent session.
  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  # Logs out the current user.
  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def current_user? user
    user&. == current_user
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
  
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  
  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to t(".ruby_on_rails"), Settings.link.home.link1 %>
    <%= link_to t(".michael"), Settings.link.home.link2 %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), about_path %></li>
      <li><%= link_to t(".contact"), '#' %></li>
      <li><%= link_to t(".news"), Settings.link.news.link1 %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".sample_app"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"),help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t(".users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
              <%= t ".account" %><b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".settings"), "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".log_out"), login_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".log_in"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
      <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
      <%= render "layouts/shim" %>
  </head>
  
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<%= provide(:title, t(".title")) %>
<!DOCTYPE html>
<html>
  <body>
    <h1><%= link_to t (".title") %></h1>
      <p>
      The 
      <%= link_to t(".link_tutorial"), Settings.link.about.link4 %> 
      , part of the
      <%= link_to t(".learn_enough"), Settings.link.about.link4 %>
      This is the sample app for the tutorial.
    </p>
  </body>
<html>

app/views/static_pages/help.html.erb
<% provide(:title, t(".title")) %>
<!DOCTYPE html>
<html>
  <body>
  	<%= link_to t("en"), locale: :en %>
  	<%= link_to t("vi"), locale: :vi %>
	<h1><%= t ".title" %></h1>
	<p>
    Get help on the Ruby on Rails Tutorial at the
		<%= link_to t(".link_help"), Settings.link.help.link2 %>
	  To get help on this sample app, see the
    <%= link_to t(".link_book"), Settings.link.help.link3 %>
	  </p>
  </body>
<html>

app/views/static_pages/home.html.erb
<% provide(:title, t(".title")) %>
<!DOCTYPE html>
<html>
  <%= link_to t("en"), locale: :en %>
  <%= link_to t("vi"), locale: :vi %>
  <body>
  <div class="center jumbotron">
  <h1><%= t ".welcome" %></h1>
    <p>
      <%= link_to t(".link_rails_tutorial"), Settings.link.home.link1 %> 
    </p>
    <%= link_to t(".sign_up"), signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  <%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200px"),"#" %>
  </body>
<html>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to t("users.new.delete"), user, method: :delete,
                                  data: { confirm: t("users.new.comfirm") } %>
  <% end %>
</li>
<br>
<hr>

app/views/users/edit.html.erb
<% provide(:title, t(".title")) %>
<h1><% t(".update") %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label t(".name") %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label t(".email") %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label t(".password") %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label t(".comfirm_pw")%>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit t(".submit"), class: "btn btn-primary" %>
    <% end %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <%= link_to t(".change"), Settings.link.user.link_avt %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, t(".title")) %>
<h1><%= t(".title") %></h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <%= render @users %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<%= provide(:title, t(".title")) %>
<h1><%= t(".title")%></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label t("users.edit.name") %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label t("users.edit.email") %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label t("users.edit.password") %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label t("users.edit.comfirm_pw") %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.submit t(".submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>